# Generated by Django 3.1.6 on 2021-04-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHIApp', '0002_propertylist_upcomingproperty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotpropertylist',
            name='BuilderName',
        ),
        migrations.RemoveField(
            model_name='hotpropertylist',
            name='Property_Amenities',
        ),
        migrations.AddField(
            model_name='propertylist',
            name='HotProperty',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=50),
        ),
        migrations.DeleteModel(
            name='HotPropertyImages',
        ),
        migrations.DeleteModel(
            name='HotPropertyList',
        ),
    ]
